# Generated by Django 5.1.2 on 2024-10-16 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUNTO_VENTA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='referencia_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PUNTO_VENTA.compra'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='referencia_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PUNTO_VENTA.pedido'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
